from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.answerLabel = QtWidgets.QLabel(Dialog)
        self.answerLabel.setGeometry(QtCore.QRect(310, 430, 71, 20))
        self.answerLabel.setObjectName("answerLabel")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 30, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 160, 50))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_4)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_16)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(330, 130, 281, 261))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.wordLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.wordLabel_2.setObjectName("wordLabel_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.wordLabel_2)
        self.slowoLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.slowoLineEdit_2.setObjectName("slowoLineEdit_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slowoLineEdit_2)
        self.exampleLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.exampleLabel_2.setObjectName("exampleLabel_2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.exampleLabel_2)
        self.descriptionLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.descriptionLabel_2.setObjectName("descriptionLabel_2")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel_2)
        self.viewsLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.viewsLineEdit_2.setObjectName("viewsLineEdit_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.viewsLineEdit_2)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.progressBar_2 = QtWidgets.QProgressBar(self.formLayoutWidget_3)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.progressBar_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.textEdit_4 = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit_4)
        self.iloscWyswietlenLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.iloscWyswietlenLabel_2.setObjectName("iloscWyswietlenLabel_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.iloscWyswietlenLabel_2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(310, 130, 20, 251))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.headerLabel = QtWidgets.QLabel(Dialog)
        self.headerLabel.setGeometry(QtCore.QRect(210, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.headerLabel.setFont(font)
        self.headerLabel.setObjectName("headerLabel")
        self.answerLineEdit = QtWidgets.QLineEdit(Dialog)
        self.answerLineEdit.setGeometry(QtCore.QRect(360, 430, 131, 20))
        self.answerLineEdit.setObjectName("answerLineEdit")
        self.mainAnswerLabel = QtWidgets.QLabel(Dialog)
        self.mainAnswerLabel.setGeometry(QtCore.QRect(50, 90, 531, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.mainAnswerLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.mainAnswerLabel.setFont(font)
        self.mainAnswerLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainAnswerLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainAnswerLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mainAnswerLabel.setMidLineWidth(10)
        self.mainAnswerLabel.setObjectName("mainAnswerLabel")
        self.shuffleButton = QtWidgets.QPushButton(Dialog)
        self.shuffleButton.setGeometry(QtCore.QRect(30, 420, 81, 31))
        self.shuffleButton.setObjectName("shuffleButton")
        self.checkButton = QtWidgets.QPushButton(Dialog)
        self.checkButton.setGeometry(QtCore.QRect(510, 410, 101, 51))
        self.checkButton.setObjectName("checkButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 70, 601, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(20, 60, 601, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(10, 400, 611, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 130, 291, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.categoryLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.categoryLabel_2)
        self.kategoriaComboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.kategoriaComboBox_2.setObjectName("kategoriaComboBox_2")
        self.kategoriaComboBox_2.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kategoriaComboBox_2)
        self.partOfSpeechLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.partOfSpeechLabel_2.setObjectName("partOfSpeechLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.partOfSpeechLabel_2)
        self.czescMowyComboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.czescMowyComboBox_2.setObjectName("czescMowyComboBox_2")
        self.czescMowyComboBox_2.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.czescMowyComboBox_2)
        self.line_4 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line_4)
        self.minDiffLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.minDiffLabel_2.setObjectName("minDiffLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.minDiffLabel_2)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider_5.setMinimumSize(QtCore.QSize(160, 22))
        self.horizontalSlider_5.setMinimum(1)
        self.horizontalSlider_5.setMaximum(10)
        self.horizontalSlider_5.setPageStep(1)
        self.horizontalSlider_5.setProperty("value", 1)
        self.horizontalSlider_5.setSliderPosition(1)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_5.setTickInterval(1)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_5)
        self.maxDiffLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.maxDiffLabel_2.setObjectName("maxDiffLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.maxDiffLabel_2)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider_6.setMinimumSize(QtCore.QSize(160, 22))
        self.horizontalSlider_6.setMinimum(1)
        self.horizontalSlider_6.setMaximum(10)
        self.horizontalSlider_6.setPageStep(1)
        self.horizontalSlider_6.setProperty("value", 10)
        self.horizontalSlider_6.setSliderPosition(10)
        self.horizontalSlider_6.setTracking(True)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setInvertedAppearance(False)
        self.horizontalSlider_6.setInvertedControls(False)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_6)
        self.line_8 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line_8)
        self.minImportanceLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.minImportanceLabel_2.setObjectName("minImportanceLabel_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.minImportanceLabel_2)
        self.horizontalSlider_7 = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider_7.setMinimumSize(QtCore.QSize(160, 22))
        self.horizontalSlider_7.setMinimum(1)
        self.horizontalSlider_7.setMaximum(10)
        self.horizontalSlider_7.setPageStep(1)
        self.horizontalSlider_7.setProperty("value", 1)
        self.horizontalSlider_7.setSliderPosition(1)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_7)
        self.maxImportanceLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.maxImportanceLabel_2.setObjectName("maxImportanceLabel_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.maxImportanceLabel_2)
        self.horizontalSlider_8 = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider_8.setMinimumSize(QtCore.QSize(160, 22))
        self.horizontalSlider_8.setMinimum(1)
        self.horizontalSlider_8.setMaximum(10)
        self.horizontalSlider_8.setPageStep(1)
        self.horizontalSlider_8.setProperty("value", 10)
        self.horizontalSlider_8.setSliderPosition(10)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setInvertedAppearance(False)
        self.horizontalSlider_8.setInvertedControls(False)
        self.horizontalSlider_8.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_8)
        self.synonymsTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.synonymsTextEdit.setGeometry(QtCore.QRect(20, 350, 291, 41))
        self.synonymsTextEdit.setObjectName("synonymsTextEdit")
        self.synonymsLabel = QtWidgets.QLabel(Dialog)
        self.synonymsLabel.setGeometry(QtCore.QRect(130, 330, 81, 16))
        self.synonymsLabel.setObjectName("synonymsLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "English Helper"))
        self.answerLabel.setText(_translate("Dialog", "Answer:"))
        self.pushButton.setText(_translate("Dialog", "ADD NEW WORD"))
        self.checkBox_3.setText(_translate("Dialog", "ENG"))
        self.checkBox_4.setText(_translate("Dialog", "PL"))
        self.label_16.setText(_translate("Dialog", "Choose language to shuffle:"))
        self.wordLabel_2.setText(_translate("Dialog", "Word:"))
        self.exampleLabel_2.setText(_translate("Dialog", "Example:"))
        self.descriptionLabel_2.setText(_translate("Dialog", "Description:"))
        self.label_17.setText(_translate("Dialog", "Accuracy"))
        self.iloscWyswietlenLabel_2.setText(_translate("Dialog", "Views::"))
        self.headerLabel.setText(_translate("Dialog", "English Helper v. 1.0"))
        self.mainAnswerLabel.setText(_translate("Dialog",
                                                "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">ANSWER CORRECT!</span></p></body></html>"))
        self.shuffleButton.setText(_translate("Dialog", "SHUFFLE"))
        self.checkButton.setText(_translate("Dialog", "CHECK!"))
        self.categoryLabel_2.setText(_translate("Dialog", "CATEGORY"))
        self.kategoriaComboBox_2.setItemText(0, _translate("Dialog", "ALL"))
        self.partOfSpeechLabel_2.setText(_translate("Dialog", "PART OF SPEECH:"))
        self.czescMowyComboBox_2.setItemText(0, _translate("Dialog", "ALL"))
        self.minDiffLabel_2.setText(_translate("Dialog", "MIN DIFFICULT"))
        self.maxDiffLabel_2.setText(_translate("Dialog", "MAX DIFFICULT:"))
        self.minImportanceLabel_2.setText(_translate("Dialog", "MIN IMPORTANCE:"))
        self.maxImportanceLabel_2.setText(_translate("Dialog", "MAX IMPORTANCE:"))
        self.synonymsLabel.setText(_translate("Dialog", "Synonyms:"))

